version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: blocker_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: flowdb
    ports:
      - "5433:5432"  # ← 올바른 배열 형식
    volumes:
      - ./postgres-data:/var/lib/postgresql/data