name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Upload project
        run: |
          tar --exclude='./node_modules' -czf app.tar.gz . --ignore-failed-read
          scp -i ~/.ssh/id_rsa app.tar.gz ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu

      - name: Remote Deploy Command
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            docker rm -f blocker_pg || true
            cd ~/ && sudo rm -rf app && mkdir app && tar -xzf app.tar.gz --strip-components=1 -C app
            cd app
            docker-compose down || true
            docker-compose up -d --build
          EOF