- name: Upload project
  run: |
    tar --exclude='./node_modules' -czf flow-backend.tar.gz .
    scp -i ~/.ssh/id_rsa flow-backend.tar.gz ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu

- name: Remote Deploy Command
  run: |
    ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
      cd ~/ && rm -rf app && mkdir app && tar -xzf flow-backend.tar.gz -C app
      cd app
      docker-compose down || true
      docker-compose up -d --build
    EOF
